### ISSUE TITLE
Spring JMS Listener Fails to Reconnect Properly via Load Balancer After Connection Drop

### ISSUE THREAD

**Issue by Hemo84** [artemiscloud/activemq-artemis-operator#1030]
We are using a Spring JMS Listener to connect to an ActiveMQ cluster deployed by operator accessible via an F5 load balancer. The load balancer is configured to route traffic to multiple brokers behind a headless service. The client application is in different openshift cluster.

**Problem**:
The listener successfully connects via the load balancer when the initial connection is established.
However, after a connection drop (e.g., network interruption or broker restart or session timeout), the Spring JMS Listener attempts to reconnect but does not connect via the load balancer's address. Instead, it tries to directly connect to a specific broker acceptor address (one of the brokers behind the load balancer). 
This behavior defeats the purpose of using a load balancer, as the reconnect bypasses the load balancing mechanism and directly targets a specific broker instance.

**Expected Behavior**:
The Spring JMS Listener should always reconnect using the load balancer's address, allowing the load balancer to manage broker selection and traffic distribution.

I really appreciate any help you can provide.

**Comment by brusdev** [comment]
@Hemo84 can you add to the question the properties that you are using to configure the connection?
