### ISSUE TITLE
Console Inaccessible in Basic Artemis Deployment

### ISSUE THREAD

**Issue by basitraza1122** [artemiscloud/activemq-artemis-operator#1048]
## Console Inaccessible in Basic Artemis Deployment

**Description:**  
I have set up a basic Artemis deployment following the [Red Hat AMQ Broker documentation](https://docs.redhat.com/en/documentation/red_hat_amq_broker/7.12/html-single/deploying_amq_broker_on_openshift/index#proc-br-setting-environment-variables_broker-container_broker-ocp). Additional services are created as expected. However, when attempting to access the console via `kubectl port-forward` on port 8161, the console remains inaccessible.

**Steps to Reproduce:**
1. Deploy Artemis using the YAML configuration provided below.
2. Expose the console by setting `spec.console.expose` to `true`.
3. Run `kubectl port-forward` on port 8161 to connect to the console. `$kubectl port-forward svc/artemis-broker-wconsj-0-svc 8161:8161`
5. Attempt to access the console in a web browser.

**Expected Behavior:**  
The console should be accessible at `localhost:8161`.

**Observed Behavior:**  
The console remains inaccessible despite following the documented steps.

**YAML Configuration:**
```yaml
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  console:
    expose: true
  deploymentPlan:
    size: 2
    persistenceEnabled: true

**Comment by basitraza1122** [comment]
![image](https://github.com/user-attachments/assets/d9c270b9-8c02-498b-a3a0-b130defdcb1f)
![image](https://github.com/user-attachments/assets/9e84f03e-3dcb-473a-92cf-1e8b78a0a736)

**Comment by basitraza1122** [comment]
Broker jolokia-access.xml file is not updated though
![image](https://github.com/user-attachments/assets/708264f9-ea5f-4dd8-877e-64a87158d8b5)

**Comment by brusdev** [comment]
This is the expected behavior because the broker pods don't listen on localhost. You could use the ingress (on Kubernetes) or the route (on OpenShift) resources created by the operator when expose is true to access the console from outside the Kubernetes/OpenShift cluster.

**Comment by basitraza1122** [comment]
Thank you, @brusdev for your assistance. I noticed that the deployment also created two ingress resources targeting the console services.

In my setup, I have two brokers, which resulted in two services and two ingress resources. If I connect to the first ingress (first broker), will I see only broker #1 data, such as addresses created and connections to broker #1, but not broker #2?

**Comment by brusdev** [comment]
> Thank you, @brusdev for your assistance. I noticed that the deployment also created two ingress resources targeting the console services.
> 
> In my setup, I have two brokers, which resulted in two services and two ingress resources. If I connect to the first ingress (first broker), will I see only broker #1 data, such as addresses created and connections to broker #1, but not broker #2?

Yes, the ActiveMQ Artemis Console only allows to access data of a single broker instance. You could use metrics to aggregate data from multiple broker instances, see https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#enable-brokers-metrics-plugin

**Comment by basitraza1122** [comment]
Thanks @brusdev I'll explore metrics aggregation further. Closing the issue now.
