### ISSUE TITLE
no kind "ActiveMQArtemis" is registered for version "broker.amq.io/v2alpha5" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28""

### ISSUE THREAD

**Issue by hafezieh** [artemiscloud/activemq-artemis-operator#112]
according to https://artemiscloud.io/blog/using_operator/ Step 3 - Deploying ActiveMQ Artemis Broker in the cloud
after creating activemq-artemis-operator when i want to create deploy/examples/artemis-basic-deployment.yaml i face this error :
no kind "ActiveMQArtemis" is registered for version "broker.amq.io/v2alpha5" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
how can i resolve that ?

OS: centos7

**Comment by gaohoward** [comment]
Hi, it looks like the CRD was not installed, make sure you successfully installed it. e.g.
$ kubectl create -f deploy/crds/broker_activemqartemis_crd.yaml

**Comment by hafezieh** [comment]
thanks for responding mr @gaohoward i delete my broker_activemqartemis_crd.yaml and create it again , and even delete whole namespace and relaunch it but i still get same error 
the output is : activemqartemis.broker.amq.io/ex-aao created
but there is no pod when i run : kubectl get pod -n myproject
and the the error in the title of this issue is result of : kubectl logs activemqartemis.broker.amq.io/ex-aao -n myproject

**Comment by gaohoward** [comment]
Hi @hafezieh 
I believe the blog is outdated. Try using the latest tag
https://github.com/artemiscloud/activemq-artemis-operator/tree/v0.20.1
When you deploy CRDs make sure there are now 4 CRDs that needs to be deployed. i.e.

kubectl create -f deploy/crds/broker_activemqartemis_crd.yaml
kubectl create -f deploy/crds/broker_activemqartemisaddress_crd.yaml
kubectl create -f deploy/crds/broker_activemqartemisscaledown_crd.yaml
kubectl create -f deploy/crds/broker_activemqartemissecurity_crd.yaml

kubectl create -f deploy/operator.yaml

**Comment by hafezieh** [comment]
sorry for bothering again , this is the whole things that i've done :
the only other thing that i can mention is , my server does not have any direct access to internet and i pulled docker imgs from my artifactory (i was carefull about versions ). does this CRDs fetch any other things from internet ?
```
[root@ activemq-artemis-operator-0.20.1]# kubectl create namespace myproject
namespace/myproject created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/service_account.yaml --namespace myproject
serviceaccount/activemq-artemis-operator created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/role.yaml --namespace myproject
role.rbac.authorization.k8s.io/activemq-artemis-operator created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/role_binding.yaml --namespace myproject
rolebinding.rbac.authorization.k8s.io/activemq-artemis-operator created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/crds/broker_activemqartemis_crd.yaml
customresourcedefinition.apiextensions.k8s.io/activemqartemises.broker.amq.io created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/crds/broker_activemqartemisaddress_crd.yaml
customresourcedefinition.apiextensions.k8s.io/activemqartemisaddresses.broker.amq.io created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/crds/broker_activemqartemisscaledown_crd.yaml
customresourcedefinition.apiextensions.k8s.io/activemqartemisscaledowns.broker.amq.io created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/crds/broker_activemqartemissecurity_crd.yaml
customresourcedefinition.apiextensions.k8s.io/activemqartemissecurities.broker.amq.io created
[root@ activemq-artemis-operator-0.20.1]# kubectl create -f deploy/operator.yaml --namespace myproject
deployment.apps/activemq-artemis-operator created
[root@ activemq-artemis-operator-0.20.1]# kubectl get pod -n myproject
NAME                                         READY   STATUS    RESTARTS   AGE
activemq-artemis-operator-59b45f7c6f-x8nc5   1/1     Running   0          28s
[root@ activemq-artemis-operator-0.20.1]# cd deploy/examples/
[root@ examples]# kubectl create -f artemis-basic-deployment.yaml -n myproject
activemqartemis.broker.amq.io/ex-aao created
[root@ examples]# kubectl get pod -n myproject
NAME                                         READY   STATUS    RESTARTS   AGE
activemq-artemis-operator-59b45f7c6f-x8nc5   1/1     Running   0          2m31s

[root@ examples]# kubectl logs activemqartemis.broker.amq.io/ex-aao -n myproject
error: no kind "ActiveMQArtemis" is registered for version "broker.amq.io/v2alpha5" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

```

**Comment by lmnetsoft** [comment]
hi @hafezieh 
I have same as your issues. Was it fixed at your side?

**Comment by lmnetsoft** [comment]
hi @gaohoward,
The readme file you mentioned is targeted for "operator" installation right? How to install ActiveMQ Artemis Broker?
I followed the official guideline here but seem it is out update https://artemiscloud.io/docs/tutorials/using_operator/ as the folder named " example" is not available in the "deploy" folder

Thanks you,

**Comment by gaohoward** [comment]
@lmnetsoft Hi the doc is a bit out of date. Once you get the operator up and running you can try to deploy a broker using one of the examples here: https://github.com/artemiscloud/activemq-artemis-operator/tree/main/examples
