### ISSUE TITLE
Upgrade to using operator-sdk 1.0

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-operator#12]
**Is your feature request related to a problem? Please describe.**
As the operator sdk has become more mature, more features have been added such as better metrics. With the move to the CNCF convergence and standardization is also taking place within Kubernetes.

**Describe the solution you'd like**
As each version bump changes how things work a little it may be the case that a big bang 0.8.2 -> 1.0 upgrade is not feasible. What might be required is to move in a more stepwise fashion through the versions to end up with the underpinnings provided by operator sdk 1.0.

**Comment by brusdev** [comment]
The operator-sdk has been upgraded to v1.15 in activemq-artemis-operator v1.0.0
