### ISSUE TITLE
Change domain name from broker.amq.io to artemiscloud.io

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by brusdev** [comment]
Changing the group of CRDs would cause backward compatibility issues.
