### ISSUE TITLE
Regarding checking addresssettings changes

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#163]
**Describe the bug**
Currently we use field by field comparison for addresssettings changes, and have different methods for each of the old versions.
It'd be worthing checking if we can use reflect.deepEqual() or something simpler to do comparison and also get rid of the old version CR comparisons (as we are going to use webhooks conversion in case user uses a older version of CR)

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
@howardgao is this issue still valid?

**Comment by brusdev** [comment]
obsolete
