### ISSUE TITLE
address controller removeFromBrokerOnDelete can be implemented with finalizers, negating the need to store/duplicate the CR in a secret

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#185]
the address controller tracks the cr in a secret and as a result can react to deletion. However this state can be stale and as a result wrong!. I would be better being stateless.
In a stateless world, rather than deleting the CR, empty and update the CR and then delete. It will achieve the same outcome.

**Comment by gtully** [comment]
unlike the artemis cr, that generates kube resources that can change independently, the address cr does not track changes to the brokers addresses. in essence, it state cannot get stale as easily. however, if it was to track broke pod restarts and a broker xml had related address changes, then in stateless mode, it would reconcile, where as today, it won't.

**Comment by brusdev** [comment]
Obsolete, ActiveMQArtemisAddress will be deprecated in favour of the field `spec.brokerProperties` of the ActiveMQArtemis CR.
