### ISSUE TITLE
Is it possible to use the operator to deploy the same instance of ArtemisAMQ on multiple kubernetes clusters? 

### ISSUE THREAD

**Issue by ghijsma** [artemiscloud/activemq-artemis-operator#213]
Hi

Currently we are running Aretmis AMQ on a single Openshift 3 cluster, using templates provided by Red Hat. We have a stateful set that provides us with 2 active running pods and a scaledown-controller.  

We are migrating to 2 new Openshift 4 clusters. In OCP4 the new way to deploy Artemis AMQ according to Red Hat is by using their operator. We want to be able to deploy Artemis AMQ on both of the clusters in an Active/Active like setup. So in this setup we would have a statefull set with 2 pods and scale-downcontroller on each of the clusters. Red Hat is not providing a sollution/support for this. We were wondering whether the Artemis AMQ opererator could do this? We have a solution to share volumes accross the 2 Openshift clusters. Traffic would be devided evenly by our F5. I know the scaledown-controller might be tricky to pull off this way.

Solution I'd like:
- The operator can be installed on multiple kubernets clusters and used to roll out one and the same Artemis AMQ cluster spread out over these multiple kubernets clusters using shared resources like volumes.

Optional alternatives we concidered (but no decissions have been made yet):
- We could move Artemis AMQ away from Openshift and run it on a VM
- We could look into another message broker
- We could move away from our multi cluster OCP4 setup
- We could spread the Artemis AMQ cluster accross the Openshift clusters if we look at them just as seperate severs?

**Comment by gaohoward** [comment]
The operator can only control it's resources within its installed cluster. I think you can try install an operator in each of your OCP 4 clusters and configure your broker the way you need. (It may not be ideal for your project but having resources across cluster boundaries seems to me beyond the scope of an operator)
