### ISSUE TITLE
new address settings configuration missing

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#217]
**Describe the bug**
In artemis 2.21.0 there are 2 new address settings added:
configDeleteDiverts
maxSizeMessages
the operator should take care of these new configuration options.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by gtully** [comment]
I think these are candidates for broker properties, it is not ideal to mix free form properties and cr attributes but it is better than replicating existing xml config as yaml and coupling the cr to broker version specific config options.
 
Longer term, I think address settings cr entries will all be implemented via properties. 
currently broker properties are intended for overrides, longer term they may go in a different properties file, address_settings.properties possibly.

**Comment by gtully** [comment]
note some examples at: https://github.com/apache/activemq-artemis/blob/main/artemis-server/src/test/java/org/apache/activemq/artemis/core/config/impl/ConfigurationImplTest.java#L698

**Comment by gaohoward** [comment]
@gtully We'll eventually go for broker properties after we deprecated this.
