### ISSUE TITLE
Getting Started Guide not updated for latest 1.0.2 operator

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-operator#234]
**Describe the bug**
Getting Started Guide does not include the installation of the security CRD or the new operator configmap.

**To Reproduce**
- Follow the steps in the Guide to attempt installation of the operator.

**Platform (please complete the following information):**
 - not platform specific

**Expected behavior**
Following the guide should result in a working operator deployment, however instead it will currently result in a CrashLoopBackoff situation.

**Additional context**
Since the Guide was updated last the operator was updated to be based on a newer operator sdk version which utilizes a configmap for some configuration, and as well the security CRD has been added but not mentioned in the Guide.

**Comment by tlbueno** [comment]
Going to be implemented by https://github.com/artemiscloud/activemq-artemis-operator/pull/733

**Comment by brusdev** [comment]
Resolved in 1.0.16
