### ISSUE TITLE
nswatch.WatchOptions.... revisit in the light of sdk watchNamespace

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#253]
This is a request to tidy up the code around namepsace support in the controller, to leaverage the capabilities and delegate to the sdk for config and options. there is currently duplicate functionality in the nswatch.WatchOptions

This has been called out in a comment for some time, may be some low hanging fruit.

https://github.com/artemiscloud/activemq-artemis-operator/blob/main/main.go#L139

**Comment by gaohoward** [comment]
Yes it's duplicated.
