### ISSUE TITLE
Question : How to handle node failures?

### ISSUE THREAD

**Issue by Mohanavalli-A** [artemiscloud/activemq-artemis-operator#284]
**Describe the bug**
On a node failure, K8s does not spin up new pods for the StatefulSets running on the node that failed. So in case of the Artemis Cloud broker cluster, it will be running with one less pod in the cluster. When there are 2 brokers in the cluster and pods are running node-1 and node-2, and say node-1 goes down, first pod-1 is unavailable for sending/receiving messages. Next say node-2 also goes down, what happens to the broker cluster? How does the operator handle this?

**To Reproduce**
1. Deploy the broker with 2 instances
2. Stop the node on which ss-1 is deployed.
3. Stop the node on which ss-0 is deployed.

**Expected behavior**
Atleast one pod should be running.

**Comment by Mohanavalli-A** [comment]
There is no option available to configure PodDisruptionBudget ? Can the operator be updated ?

**Comment by brusdev** [comment]
Resoved by #442
