### ISSUE TITLE
Question: Option to deploy with clusterIp (not headless)

### ISSUE THREAD

**Issue by dlystra** [artemiscloud/activemq-artemis-operator#285]
We have a tenant using AMQ Broker, but the service is only balancing the connections between 3 of the replicas. How can I set the operator to allow loadbalancing between all AMQ Broker pods? We tried replacing a headless service with clusterIp and it seemed to randomize the connections sufficiently. Is there an option for this or another way to ensure we are loadbalancing evenly? Thanks.

**Comment by gaohoward** [comment]
Hi, currently the operator doesn't support this. You need to install your own loadbalancer.
