### ISSUE TITLE
Error in operator logs

### ISSUE THREAD

**Issue by thoraage** [artemiscloud/activemq-artemis-operator#298]
**Describe the bug**
 I consistently get this stacktrace in the operator logs:

    2022-09-07T05:51:29.915Z        INFO    package k8s_actions     Creating new *v1.Secret {"ActiveMQArtemis Name": "amq-app-secret", "Namespace": "amq"}
    2022-09-07T05:51:29.919Z        ERROR   package k8s_actions     Failed to create new *v1.Secret {"ActiveMQArtemis Name": "amq-app-secret", "Namespace": "amq", "error": "resourceVersion should not be set on objects to be created"}
    github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).ProcessResources
            /remote-source/app/controllers/activemqartemis_reconciler.go:1170
    github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconcilerImpl).Process
            /remote-source/app/controllers/activemqartemis_reconciler.go:129
    github.com/artemiscloud/activemq-artemis-operator/controllers.(*ActiveMQArtemisReconciler).Reconcile
            /remote-source/app/controllers/activemqartemis_controller.go:142
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
            /remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
            /remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
            /remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
    sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
            /remote-source/app/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227

I'm not sure why the operator is trying to **create** the secret I've configured in console.sslSecret-attribute of my ActiveMQArtemis-yaml. It assume it must have read it since it get the resourceVersion-attribute.

**To Reproduce**
Create ActiveMQArtemis-instance with console.sslSecret-attribute configured to already existing secret.

**Platform (please complete the following information):**
 - Operator image 7.10-15

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
Issue fixed by #353
