### ISSUE TITLE
Not able to execute go tests

### ISSUE THREAD

**Issue by bahetiamit** [artemiscloud/activemq-artemis-operator#3]
I created the AMQ image using attached subset of AMQ multistage docker file
[Dockerfile.txt](https://github.com/artemiscloud/activemq-artemis-operator/files/5103441/Dockerfile.txt).

Created the container and went to the container shell & tried to execute `go test ./pkg/controller/... -v -count=1 -list Test*`  resulting in failure as shown below

```
bash-4.2$ go test ./pkg/controller/... -v -count=1 -list Test*
# github.com/artemiscloud/activemq-artemis-operator/pkg/controller/broker/v2alpha2/activemqartemis [github.com/artemiscloud/activemq-artemis-operator/pkg/controller/broker/v2alpha2/activemqartemis.test]
pkg/controller/broker/v2alpha2/activemqartemis/mocks_test.go:151:119: undefined: environments.MakeEnvVarArrayForCR
pkg/controller/broker/v2alpha2/activemqartemis/mocks_test.go:159:9: undefined: pods.NewPodTemplateSpecForCR
?       github.com/artemiscloud/activemq-artemis-operator/pkg/controller        [no test files]
?       github.com/artemiscloud/activemq-artemis-operator/pkg/controller/broker/v2alpha1/activemqartemisscaledown      [no test files]
FAIL    github.com/artemiscloud/activemq-artemis-operator/pkg/controller/broker/v2alpha2/activemqartemis [build failed]
?       github.com/artemiscloud/activemq-artemis-operator/pkg/controller/broker/v2alpha2/activemqartemisaddress [no test files]
FAIL
```

I would like to know the validation steps for the container.

**Comment by RoddieKieley** [comment]
@bahetiamit Sorry for the delay in getting an update here. In testing the current master at artemiscloud, where further development is now occurring, commit [06f1e00aff08ba57af81faa4b0d9fd74a74f87ff](https://github.com/artemiscloud/activemq-artemis-operator/commit/06f1e00aff08ba57af81faa4b0d9fd74a74f87ff) with  
> export GOPROXY=https://proxy.golang.org
to work around the [openshift api tagging issue](https://github.com/openshift/api/issues/456) I now see that the tests run using the command above.

Please give this a try from the current artemiscloud based master at [06f1e00aff08ba57af81faa4b0d9fd74a74f87ff](https://github.com/artemiscloud/activemq-artemis-operator/commit/06f1e00aff08ba57af81faa4b0d9fd74a74f87ff) and let us know if it continues to not work for you.

**Comment by pshields2** [comment]
@brushdev, 
I eventually tracked the root cause of this issue in my system and it turns out a USER 1000 directive was added to the rebuild of the activemq-artemis-broker-kubernetes image and thus the image was running under that UID.

**Comment by brusdev** [comment]
@pshields2 thanks for sharing your findings
