### ISSUE TITLE
Unable to deploy the Artemis broker

### ISSUE THREAD

**Issue by minhtran-q** [artemiscloud/activemq-artemis-operator#308]
**Describe the bug**
I'm trying to start Artemis Cloud. I have followed each step in the quick start guide, but I am having trouble **deploying the broker**. 

The error shown on the Kubernetes dashboard is:
```
Failed to pull image "quay.io/artemiscloud/activemq-artemis-broker-init:2.23.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/artemiscloud/activemq-artemis-broker-init:2.23.0 not found: manifest unknown: manifest unknown
```
![image](https://user-images.githubusercontent.com/26593630/191683592-2076d66d-96ca-4426-af8b-94fd280e662b.png)

**To Reproduce**
1. Deploying the operator.
2. Execute `kubectl create -f examples/artemis-basic-deployment.yaml -n activemq-artemis-operator`.

**Platform (please complete the following information):**
 - OS: WSL2
 - Go 1.17.8
 - operator-sdk version: "v1.15.0"
 - minikube version: v1.27.0

Am I doing something wrong at any step?

**Comment by brusdev** [comment]
Cannot reproduce on 1.0.17
