### ISSUE TITLE
Unable to deploy operator on Mac OS

### ISSUE THREAD

**Issue by PMacho** [artemiscloud/activemq-artemis-operator#309]
**Describe the bug**

I use a clean clone of the actual master type 

`make deploy`

That fails saying:

> go: added sigs.k8s.io/structured-merge-diff/v3 v3.0.0
go: added sigs.k8s.io/yaml v1.2.0
cd config/manager && /Users/pema/projects/kubernetes_playground/apache_active_mq_artemis/activemq-artemis-operator/bin/kustomize edit remove resource webhook_secret.yaml 
bash: /Users/pema/projects/kubernetes_playground/apache_active_mq_artemis/activemq-artemis-operator/bin/kustomize: No such file or directory

**To Reproduce**
1. `git clone https://github.com/artemiscloud/activemq-artemis-operator.git`
2. `cd activemq-artemis-operator`
3. `make deploy`

**Platform (please complete the following information):**
 - OS: Mac OS
 - Version: 12.6 (21G115)
 - Go: go1.19.1 darwin/amd64

**Additional context**
I am on Apple M1.

**Comment by eric-engberg** [comment]
I am also having this problem.  even running 'make kustomize' doesn't seem to download the kustomize binary.. though I do already have kustomize installed on my Mac

**Comment by brusdev** [comment]
Could you try using the same golang version defined in the [go.mod](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/go.mod) file?

**Comment by brusdev** [comment]
Cannot Reproduce
