### ISSUE TITLE
When deploying into kubernetes cluster or docker container ": invalid option"

### ISSUE THREAD

**Issue by josefsilva013** [artemiscloud/activemq-artemis-operator#317]
**Describe the bug**
I built a custom operator image with certs and when i deploy into the cluster i get this error ": invalid option" the image gets pulled fine and the pod gets deployed but crashes. I also tried to deploy it in just a docker container and ran it with docker run and the same error appears

**To Reproduce**
1. build an image with a redhat base image and hard code the broker_name directory 
2. '...'

**Platform (please complete the following information):**
 - OS: redhat UBI-8
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
Cannot reproduce on 1.0.17
