### ISSUE TITLE
Support LDAPLoginModule

### ISSUE THREAD

**Issue by borcsokj** [artemiscloud/activemq-artemis-operator#351]
**Is your feature request related to a problem? Please describe.**
LDAPLoginModule is not supported by operator but ActiveMQ Artemis only.

**Describe the solution you'd like**
Handle new properties similar to Properties (or Keycloak) login modules.

**Describe alternatives you've considered**
Properties can be set by environment variable (from ConfigMap or Secret) but custom post-config.sh shell script is required. Kubernetes configuration is more complex (holding simple values vs. complete Artemis configuration file/fragment) in that case.

**Comment by brusdev** [comment]
@borcsokj thansk for your contribution, the operator now supports configurable JAAS authentication, for further details see #356 . Feel free to create a new issue if configurable JAAS authentication doesn't work for you.
