### ISSUE TITLE
Configurable JAAS authentication

### ISSUE THREAD

**Issue by ruromero** [artemiscloud/activemq-artemis-operator#356]
**Is your feature request related to a problem? Please describe.**
In order to limit the StatefulSet rollouts and custom initContainer implementations it should be possible to externalize the authentication users and roles.

**Describe the solution you'd like**
A predefined suffix for the configmap added to the extraMounts (e.g. -jaas-config) might be used to configure the broker JAAS authentication. This configMap or secret must contain the login.config. This login.config may or may not reference the user and roles properties in this same configMap/secret.

**Comment by gtully** [comment]
implemented in https://github.com/artemiscloud/activemq-artemis-operator/commit/858c305b09ef57c47a249f6755aa400ce7ad0c3b
