### ISSUE TITLE
Artemis operator on Openshift on AWS with "expose: true" on acceptors doesn't expose those ports to the outside

### ISSUE THREAD

**Issue by bergner** [artemiscloud/activemq-artemis-operator#358]
**Brief summary**
This issue is about understanding how raw TCP ports like AMQP and STOMP ports are supposed to be exposed to services running outside the Openshift cluster. As far as I can tell it does not work because services of type ClusterIP are created and the Openshift Routes only deals with http-esque routing or possibly TLS/SNI based routing which can also contain a routable "host name". Neither AMQP or STOMP fit those capabilities of a Route and there is no NodePort exposed through which port based routing from a load balancer could be configured.

**Describe the bug**

Deploying Artemis operator in Openshift on AWS with this configuration currently. I was specifically looking to ensure STOMP connectivity worked. The CORE part is there because I thought that could be necessary for clustering and AMQP was just an extra protocol I added.

````
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: test-amq
spec:
  acceptors:
  - name: core
    protocols: CORE
    port: 61616
    expose: false
  - name: amqp
    protocols: AMQP
    port: 5672
    expose: true
  - name: stomp
    protocols: STOMP
    port: 61613
    expose: true
  deploymentPlan:
    size: 2
````

**Inside the cluster**

The two pods are deployed and based on the logs it looks like they connect to each other properly because the logs contain "Bridge ClusterConnectionBridge@60f731c6 ... is connected".

I can connect to the service inside the cluster on port 61613 and can do STOMP messaging ok there. The operator setup these services and routes (Openshift's flavor of ingress):

````
$ oc get svc
test-amq-amqp-0-svc    ClusterIP      172.30.120.105   <none>                                 5672/TCP             5h39m
test-amq-amqp-1-svc    ClusterIP      172.30.45.178    <none>                                 5672/TCP             5h39m
test-amq-core-0-svc    ClusterIP      172.30.218.42    <none>                                 61616/TCP            5h39m
test-amq-core-1-svc    ClusterIP      172.30.210.93    <none>                                 61616/TCP            5h39m
test-amq-hdls-svc      ClusterIP      None             <none>                                 8161/TCP,61616/TCP   5h39m
test-amq-ping-svc      ClusterIP      None             <none>                                 8888/TCP             5h39m
test-amq-stomp-0-svc   ClusterIP      172.30.242.130   <none>                                 61613/TCP            5h39m
test-amq-stomp-1-svc   ClusterIP      172.30.222.248   <none>                                 61613/TCP            5h39m

$ oc get route
test-amq-amqp-0-svc-rte    test-amq-amqp-0-svc-rte-default.apps.testokd.aws1.example.com           test-amq-amqp-0-svc    amqp-0                  None
test-amq-amqp-1-svc-rte    test-amq-amqp-1-svc-rte-default.apps.testokd.aws1.example.com           test-amq-amqp-1-svc    amqp-1                  None
test-amq-stomp-0-svc-rte   test-amq-stomp-0-svc-rte-default.apps.testokd.aws1.example.com          test-amq-stomp-0-svc   stomp-0                 None
test-amq-stomp-1-svc-rte   test-amq-stomp-1-svc-rte-default.apps.testokd.aws1.example.com          test-amq-stomp-1-svc   stomp-1                 None
````
On AWS there are load balancers which currently forward ports 443 -> 32550 and 80 -> 30979 to the Kubernetes worker nodes and those ports on the nodes have the "ovnkube" process (the OVN-Kubernetes CNI) listening on those ports, which I assume goes into the Openshift router.

Since all the created services are of type "ClusterIP" and Openshift Routes seem to only care about http-esque host based routing I don't see how I could allow something outside the cluster to connect to either the AMQP or STOMP ports since they don't meet the requirement of the host based routing.

````
$ oc get route test-amq-stomp-0-svc-rte -o yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-10-26T09:41:44Z"
  labels:
    ActiveMQArtemis: test-amq
    application: test-amq-app
    statefulset.kubernetes.io/pod-name: test-amq-ss-0
  name: test-amq-stomp-0-svc-rte
  namespace: default
  ownerReferences:
  - apiVersion: broker.amq.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ActiveMQArtemis
    name: test-amq
    uid: 582fdcc0-dfa2-48f9-8ec2-986b8cf1523b
  resourceVersion: "48061657"
  uid: 8a4284c1-cbc6-46ce-bf58-a18fdd2eaacc
spec:
  host: test-amq-stomp-0-svc-rte-default.apps.testokd.aws1.example.com
  port:
    targetPort: stomp-0
  to:
    kind: Service
    name: test-amq-stomp-0-svc
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2022-10-26T09:41:44Z"
      status: "True"
      type: Admitted
    host: test-amq-stomp-0-svc-rte-default.apps.testokd.aws1.example.com
    routerCanonicalHostname: router-default.apps.testokd.aws1.example.com
    routerName: default
    wildcardPolicy: None
````

**Questions**

* Is it at all supported to expose raw AMQP and/or STOMP port access outside the cluster using the Artemis operator?
* Would it work if AMQP/STOMP + TLS is used and the client libraries used set the server name (SNI) in the TLS ClientHello? Is this the recommended way to route such traffic?
* Shouldn't "expose: true" imply that services of type NodePort are used for the raw TCP ports so that it is possible to route traffic to those ports from a load balancer since name/path based routing doesn't really work for such protocols? Or is there some option to the operator that would enable this? The only occurrences of NodePort in the code are in a test so I'm pretty sure the answer is no here.

**To Reproduce**

1. Deploy operator on cluster with above configuration.
2. Try to access AMQP or STOMP service through AWS load balancer.
3. No port exposed on load balancer makes this impossible.
4. Try to figure out how to add a port mapping to the load balancer.
5. Realize there is no port on the servers the load balancer could forward traffic to/from.

**Platform (please complete the following information):**
 - OKD 4.10 on AWS
 - Cluster installed with openshift-install installer
 - Artemis operator installed using docs/quickstart.md instructions from this repo for cluster wide install

**Expected behavior**

Some possibility to route AMQP/STOMP traffic from outside the cluster.

I'm fine with the answer being that TLS/SNI is mandatory, I just haven't found anything that explicitly states that is the intended behavior.

**Comment by eric-engberg** [comment]
I'm having the same issue with EKS.  I also don't see a way to expose the metrics port. not sure how to enable that.

**Comment by brusdev** [comment]
Only the acceptors with ssl enabled can be accessed from outside the Kubernetes/OpenShiftcluster, for further details about the acceptors with ssl enabled see https://artemiscloud.io/docs/tutorials/ssl_broker_setup/#prepare-the-broker-cr-with-ssl-enabled
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  adminUser: admin
  adminPassword: admin
  deploymentPlan:
    size: 1
  acceptors:
  - name: sslacceptor
    protocols: all
    port: 61617
    expose: true
    sslEnabled: true
```

Produce messages from outside the cluster using the artemis CLI
```
artemis producer --destination queue://test --user admin --password admin --protocol core --url ssl://<ACCEPTOR_ROUTE_HOST>:443
```
