### ISSUE TITLE
Single line install

### ISSUE THREAD

**Issue by hguerrero** [artemiscloud/activemq-artemis-operator#371]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Have a single line `apply -f` command to install the operator for either single namespace watch of cluster wide.

Currently running a Shell script creates friction.

**Describe alternatives you've considered**
Create my own, or do a script for that.

**Additional context**
Installing the operator on minikube should be as easy as possible.

**Comment by brusdev** [comment]
A yaml file for installing the operator cluster wide was added by #748 while the a yaml for single namespace can not be added because it has to be dynamically generated.
