### ISSUE TITLE
Canot local build

### ISSUE THREAD

**Issue by lultala** [artemiscloud/activemq-artemis-operator#379]
I want rebuild image with custom image for broker, because if i change image for custom in example file artemis-basic-deployment , hi want downloads image quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.26.0.
So when i try make, make build,  make OPERATOR_IMAGE_REPO=test OPERATOR_VERSION=1.1 docker-build
i have error 
```
cd config/manager && /Users/lultala/work/test/activemq-artemis-operator/bin/kustomize edit remove resource webhook_secret.yaml 
bash: /Users/lultala/work/test/activemq-artemis-operator/bin/kustomize: No such file or directory
make: *** [manifests] Error 127
```
How i can change broker image?

**Comment by djarillo** [comment]
Similar error...

bash: line 1: /home/activemq/activemq-artemis-operator/bin/controller-gen: No such file or directory
make: *** [Makefile:111: generate] Error 127

go version go1.19.3 linux/amd64
operator-sdk version: "v1.25.1"

**Comment by gaohoward** [comment]
Please try to use go 1.17 instead, we don't support go 1.19 yet. (there is
a task for that)
