### ISSUE TITLE
Voting: shortNames for CRDs

### ISSUE THREAD

**Issue by michalxo** [artemiscloud/activemq-artemis-operator#408]
We are going to implement shotNames for CRDs. It would be cool, if people could participate and vote in some way in github on preferred names. For more information please see #395 

List of CRD "prefix" candidates are:
- `aa`   (1)
- `ac`   (4)
- `amq` (0)

So resulting usage in case `aa` prefix wins, will be for example:
`aa` - _ActiveMQArtemis CR/D_
`aaa` - _ActiveMQArtemisAddress_
`aas` - _ActiveMQArtemisSecurity_
`aad` - _ActiveMQArtemisScaleDown_

To vote, please just comment with specified shortName you like. I will be regularly updating this comment with number of votes.
Deadline for voting will be end of this Friday 2022-12-09.

**Comment by brusdev** [comment]
I vote for `ac` to enforce the `ArtemisCloud` brand

**Comment by aboucham** [comment]
I vote for `ac` as well. Good initiative @michalxo :-)

**Comment by tlbueno** [comment]
I vote for AC

**Comment by rvais** [comment]
AC makes the most sense ...
