### ISSUE TITLE
To allow configure log level for the operator via configmap

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#420]
**Is your feature request related to a problem? Please describe.**
When deploy the operator manually user can directly edit the yaml to set the log level. However
when operator is deployed with olm, that wouldn't work. A configmap should be provided as
a way to solve this. The operator at its startup will look for this configmap to init the log level.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by gtully** [comment]
I think the config map should be of the general cmd_line_args_append format. and support any argument addition. A map of the yaml "args"

**Comment by gtully** [comment]
the ARGS env is great.
