### ISSUE TITLE
Question : What is the maximum allowed length for the broker name?

### ISSUE THREAD

**Issue by Mohanavalli-A** [artemiscloud/activemq-artemis-operator#422]
Name for services, config maps, pv, pvc , etc linked to the broker are calculated by adding prefix and/or suffix to the broker name configured in the yaml. Since kubernetes names and labels are restricted to a maximum of 63 characters, long broker names lead to deployment failure due to invalid names of the related services.
For example, when deploying a broker with name `eeee-zzzzzzzz-ssssssssssssssssssss-app-broker`  with the below configuration,
````
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: eeee-zzzzzzzz-ssssssssssssssssssss-app-broker
````
deployment fails with below error.
````
Warning  FailedCreate      4m19s (x19 over 26m)  statefulset-controller  create Pod sit-itaagxx-westeuropeazure01-eesb-broker-ss-0 in StatefulSet eeee-zzzzzzzz-ssssssssssssssssssss-app-broker-ss failed error: Pod "eeee-zzzzzzzz-ssssssssssssssssssss-app-broker-ss-0" is invalid: [spec.volumes[1].name: Invalid value: "configmap-eeee-zzzzzzzz-ssssssssssssssssssss-app-broker-props-00000001": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not found: "configmap-eeee-zzzzzzzz-ssssssssssssssssssss-app-broker-props-00000001", spec.initContainers[0].volumeMounts[2].name: Not found: "configmap-eeee-zzzzzzzz-ssssssssssssssssssss-app-broker-props-00000001"]`
````
Can you clarify what is the allowed length for the broker names?

**Comment by brusdev** [comment]
The broker name is used as the prefix for the names of the resources related created by the operator for the ActiveMQArtemis CR. It is hard to predict because it depends on the resources required but the validation conditions in the ActiveMQArtemis CR should provide a sufficient feedback.
