### ISSUE TITLE
Adding support for user-provided init container

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#43]
**Is your feature request related to a problem? Please describe.**
Provide a way for the user to use their own init container to config broker

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by rohanmars** [comment]
This feature is need to do a chmod on the data directory in non opernshitf environment.

**Comment by gaohoward** [comment]
I think it's been implemented. Closing it.
