### ISSUE TITLE
Improving version handling in the CR

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#430]
**Is your feature request related to a problem? Please describe.**

It would be worth considering that what if we are to do some version aware code in the operator, do we need to drop the image url option? Or do we have a way to extract the version from the image?

If we can't easily infer the version from the image, and if it is a custom image I think we can't without some authenticated query to the registry, do we need to support some sort of "-final" postfix to a version string to say - no updates.
Even that will be problematic if the mapped image url changes under the hood, we will need to annotate the CR to mark the first image we resolved to in the -final case. This may not be ideal.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by gtully** [comment]
https://github.com/artemiscloud/activemq-artemis-operator/issues/516 will help clarify and with usability

**Comment by gtully** [comment]
I think the only way we can have a final version is through the image field where that value is a fully qualified hash/sha that is paired with an initImage. Until we find a burning need, I think we can leave the operator version agnostic, using the supported range to allow safe usage of newer features when necessary and gateing other features on CR fields as necessary
