### ISSUE TITLE
Missing generated fields in deploy artemis crd

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#440]
**Describe the bug**
The externalConfigs field added in artemis CRD is not generated into the crd in deploy/install.
(running make generate-deploy fixes it). Also the generated *deepcopy.go 

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by gtully** [comment]
this is not good, how did you find this?

**Comment by gaohoward** [comment]
I was building the source for another issue and found that. :)

**Comment by brusdev** [comment]
we should add a check for the generated files in the ci workflow to avoid similar

**Comment by brusdev** [comment]
Check added to the ci workflow, see https://github.com/artemiscloud/activemq-artemis-operator/commit/865781812dc7f2281ef799ff363ebf9129094db9
