### ISSUE TITLE
Metrics from operator to prometheus

### ISSUE THREAD

**Issue by sun-shard** [artemiscloud/activemq-artemis-operator#453]
Good afternoon. There was a need to receive metrics in Prometheus from the Artemis operator. Please let me know what are the ways to solve this problem. In other issue I saw that you only plan to add this functionality
At the moment, I have a configured prometheus, with auto-search and addition of all services. Writes the wrong path to all Artemis services

**Comment by brusdev** [comment]
This feature has been already developed and it will be included in v1.0.8, for further details see #384
