### ISSUE TITLE
extra mount watch is too simplistic and potentially costly

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#457]
To track the status of referenced resources in #429 a new watch was added on config maps and secrets.

https://github.com/artemiscloud/activemq-artemis-operator/commit/c6f69135df6c6b583c5bcc4d7c683f0b2930b95c#diff-4b39fd9a9f5927e7fa6934d6892919f2ef47e81568ec6908feafcac119d52347

The filter tracks the extramounts on our CRs, even with no extramounts, we still have the watch events.

it would be better if we could have a watch per cr extra mount, 100s of watches rather than 10000s of watch events.

We would need to find a good stateless way to map watchers to CRs.extramounts such that reconcile is idempotent

**Comment by gtully** [comment]
This was the inspiration for the existing watch https://book.kubebuilder.io/reference/watching-resources/externally-managed.html

we need a deep dive into the watch logic to see if 1) it can be dynamic 2) watches can be identified

**Comment by gtully** [comment]
requiring that the referenced config map has a label - ActiveMQArtemis or something like that - there may be some existing well known label for references, verifying that on CR creation and then using that as a filter may be the way to go.

If the user has to apply the label to get it to work we can depend on the label

**Comment by ruromero** [comment]
When the `findCrWithReferenceToResource` handler method is called, the information is already dynamic and depends on the current state of the CR so I don't think labels are going to simplify the watch function. From the CR we can know which extraConfigs are relevant. Imposing a user to add a label would not add any value IMO.

It seems the reference link you added is the way to implement watches so we should keep it like this.

**Comment by gtully** [comment]
If the watch is filtered by label, we will get very limited events, at a min we will not be spinning our wheels looking for non existent matches in our CRs for all secrets and config maps. 
Extra configs will be created for the broker, I think it a very small tax to ask for a label/annotation and will greatly limits the quantity of events we have to react to.

**Comment by ruromero** [comment]
If I'm not understanding the code wrong. The cost is very similar. Currently the cm/secrets are passed and if the name matches with one of the extraMounts then a reconcile request is created. With labels is similar, the same resource is passed and then the code will check that the resource contains such label.

**Comment by gtully** [comment]
It it a case of there the filter is applied? But even so, It will cut off a whole bunch of events at source. If the source is the API server it is perfect, or it is just the local cache, I guess we don't care.
I am thinking this sort of thing with predicate.LabelSelectorPredicate :
https://github.com/heimdall-controller/watcher-prototype/blob/e2748e7dd5e5142894978b7ee120f15d021dad3a/controllers/pod_controller.go#L47

**Comment by gtully** [comment]
The more I think on this, with all filtering on the cache, either we cache just metadata and make use of the dual cache and direct client etc, and live with the memory overhead or having all objects locally...

or we abandon the watch and do a periodic reconcile on any CR that has extramounts.

Having an accurate status is the use case for the watch. Maybe we can live with status being updated every 30s?
