### ISSUE TITLE
 test case failing on ppc64 <quay.io/artemiscloud/fake-broker:latest>

### ISSUE THREAD

**Issue by BhimraoPatil** [artemiscloud/activemq-artemis-operator#460]
**Describe the bug**
The specific test is passing on amd64 architecture but its failing on ppc64 architecture
amd64 : https://github.com/artemiscloud/activemq-artemis-operator/actions/runs/3832489461/jobs/6522853579
ppc64 :
 Timed out after 30.000s.
  Expected success, but got an error:
      <*errors.errorString | 0xc000121870>: {
          s: "Assertion in callback at /activemq-artemis-operator/controllers/activemqartemis_controller_test.go:260 failed:\nExpected\n    <string>: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.27.0\nto equal\n    <string>: quay.io/artemiscloud/fake-broker:latest",
      }
      Assertion in callback at /activemq-artemis-operator/controllers/activemqartemis_controller_test.go:260 failed:
      Expected
          <string>: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.27.0
      to equal
          <string>: quay.io/artemiscloud/fake-broker:latest
  In [It] at: /activemq-artemis-operator/controllers/activemqartemis_controller_test.go:264

**To Reproduce**
1. Installation of Go
2. Cloning the repo
3. make build
4. make test

**Platform (please complete the following information):**
 - OS: Linux 8521f304d74a 4.18.0-372.9.1.el8.ppc64le
 - Version : Master
 - Go:  1.17

**Comment by brusdev** [comment]
The support for other architectures as ppc64 will be added updating the operator-sdk, for further details see #256
