### ISSUE TITLE
provide some validation of the contents of a login.config key in the -jaas-config suffix secret extra mount

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#495]
The format of a jaas login config is error prone, it would be nice if the operator could catch trivial errors like missing semi colons etc.
In that way, if the auth on the broker is broken due to and invalid login.config update, the status can reflect that.
For new CR's, validation can avoid some simple mistakes. It can never be perfect because the referenced login modules won't be exercised, but catching syntax errors could be a real help.

**Comment by gtully** [comment]
The validation uses a regex - the regex can be configured or disabled via the operator manager env var: JAAS_CONFIG_SYNTAX_MATCH_REGEX

**Comment by brusdev** [comment]
That regex is incredible!!! Are you [Neo](https://en.wikipedia.org/wiki/Neo_(The_Matrix)) ?
