### ISSUE TITLE
"failed to create or get service for metrics" logged w/update to operator sdk v0.8.2

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-operator#5]
**Describe the bug**
After the commit of PR#2 to 'migrate from dep to go mod and upgrade the version of sdk v0.8.2' the following error is seen in the logs:

`{"level":"info","ts":1597843133.2972333,"logger":"cmd","msg":"failed to create or get service for metrics: services \"activemq-artemis-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"}`

**To Reproduce**
1. Get the master version of the source from after PR#2 was merged.
2. Deploy the broker operator

**Platform (please complete the following information):**
 - OS: RHEL
 - Version: 7.6
 - Go: 1.13.4
 - OCP: 3.11

**Comment by redhatHameed** [comment]
Fixed in https://github.com/artemiscloud/activemq-artemis-operator/pull/7

logs showing now 
```
{"level":"info","ts":1598472595.2815452,"logger":"metrics","msg":"Metrics Service object created","Service.Name":"activemq-artemis-operator","Service.Namespace":""}
```

**Comment by gaohoward** [comment]
close as fixed
