### ISSUE TITLE
support headless services, listeners are set up for each IP:Port pair in the headless service.

### ISSUE THREAD

**Issue by ramu11** [artemiscloud/activemq-artemis-operator#503]
proposal to add the port 7800 to the headless service makes sense to me:
https://istio.io/latest/docs/ops/configuration/traffic-management/traffic-routing/#headless-services

refer [491](https://github.com/artemiscloud/activemq-artemis-operator/discussions/491)

**Comment by brusdev** [comment]
This enhancement will be included in 1.0.17
