### ISSUE TITLE
Fix client code gen issue and proper doc

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#51]
**Describe the bug**
Currently when we bump the crds the client api code cannot be generated by operator-sdk
the code-gen util seems broken. Fix it and add proper doc.

**To Reproduce**
1. Get X version of the source
2. '...'

**Platform (please complete the following information):**
 - OS: [e.g. Fedora]
 - Version [e.g. 32]
 - Go [e.g. 1.13.4

**Expected behavior**
Optional, use if not obvious. A clear and concise description of what you expected to happen.

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
Optional. Add any other context about the problem here.

**Comment by brusdev** [comment]
Fixed upgrading operator-sdk.
