### ISSUE TITLE
Can not use retain message when deploying 2 pods with deploymentPlan.size 2

### ISSUE THREAD

**Issue by nghialenhut** [artemiscloud/activemq-artemis-operator#519]
**Describe the bug**
Can not use retain message when deploying 2 pods with deploymentPlan.size 2

The deployment used  as below
    persistenceEnabled: true
    messageMigration: true
    clustered: true 
    deploymentPlan.size 2

**To Reproduce**
1. Sending the message to MQTT broker with retain message option, Ex: mosquitto_pub -h 192.168.0.100 -p 1883 -t 'test' -m "{\"presence\":1}" -q 1 -r 
2. Consume the message, Ex: mosquitto_sub -h 192.168.0.100 -p 1883 -t 'test'

**Platform (please complete the following information):**
 - OS: AKS
 - Version 1.21.9
 - Using Service type load balance: 192.168.0.0

**Expected behavior**
The retained message always is received

**Screenshots**
Optional, add screenshots to help explain your problem.

**Additional context**
If consuming on each broker (pod) then only have the retain message on a broker.
Ex: We have 2 brokers with IP 192.168.0.101 & 192.168.0.102 then consuming on broker 1 (192.168.0.101) has the retain message but broker 2 is not, Otherwise if consuming on broker 2 (192.168.0.101) has the retain message but broker 1 is not.

**Comment by brusdev** [comment]
@nghialenhut this seems a question for Apache ActiveMQ Artemis users mailing list [users@activemq.apache.org](mailto:users@activemq.apache.org) why do you think it is related to the ArtemisCloud Operator?

**Comment by gtully** [comment]
I think this needs to be addressed with in Artemis, I imagine a retain feature building on last value queue (LVQ) but I am not sure what semantics are desired for an LVQ in a cluster. It would need some investigation.
