### ISSUE TITLE
Allow to customize keystore and trustore filename and password via CR

### ISSUE THREAD

**Issue by pabateman** [artemiscloud/activemq-artemis-operator#520]
**Is your feature request related to a problem? Please describe.**
In our organization we use artemis-operator and manage **all of** PKI infrastructure with [cert-manager](https://cert-manager.io/). It's supports Java's keystores and trustores as certificate output format but doesn't allow to customize key names and sets default as `truststore.jks` and `keystore.jks`. In [the code](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/controllers/activemqartemis_reconciler.go#L938-L941):

```
	keyStorePassword := "password"
	keyStorePath := "\\/etc\\/" + secretName + "-volume\\/broker.ks"
	trustStorePassword := "password"
	trustStorePath := "\\/etc\\/" + secretName + "-volume\\/client.ts"
```

 I see that keystore and trustore names and passwords are hardcoded.

**Describe the solution you'd like**
I would like to set up this in acceptor spec (i.e. for each `SSLSecret`) or at least for broker instance. For example, add additional fields in [AcceptorType](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/api/v1beta1/activemqartemis_types.go#L406) and [ConnectorType](https://github.com/artemiscloud/activemq-artemis-operator/blob/main/api/v1beta1/activemqartemis_types.go#L478) that has truststore settings too. I can contribute if you don't mind of course.

Best regards!

**Comment by brusdev** [comment]
ArtemisCloud ActiveMQ Artemis Operator supports custom keyStore and trustStore paths adding keyStorePath and trustStorePath entries to the acceptor secret, i.e. supposing the name of the secret created by jetstack cert-manager is broker-cert-secret, the solution is to create an acceptor secret with keyStorePath and trustStorePath entries and to define an extra mount for broker-cert-secret:

oc create secret generic my-acceptor-secret \
--from-literal=keyStorePath=/amq/extra/secrets/broker-cert-secret/keystore.jks \
--from-literal=trustStorePath=/amq/extra/secrets/broker-cert-secret/truststore.jks \
--from-literal=keyStorePassword=<password> \
--from-literal=trustStorePassword=<password>

apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  acceptors:
    - name: my-acceptor
      sslEnabled: true
      sslSecret: my-acceptor-secret
      ...
  deploymentPlan:
    extraMounts:
      secrets:
        - broker-cert-secret
...

**Comment by pabateman** [comment]
Works like a charm, thanks!
