### ISSUE TITLE
Support for adding custom annotations to the broker statefulset

### ISSUE THREAD

**Issue by mattlegall** [artemiscloud/activemq-artemis-operator#546]
**Is your feature request related to a problem? Please describe.**
I want to add the annotation below at broker statefulset level:
reloader.stakater.com/auto: "true"
The idea is to get the broker pod to restart whenever the configmap changes (I am using configmap to mount config files like artemis-roles.properties into the broker pod)

**Describe the solution you'd like**
Currently, I am adding annotations at broker pod level using spec/deploymentPlan/annotations. Proposal could be to have similar spec/deploymentPlan/statefulsetAnnotations

**Comment by brusdev** [comment]
@mattlegall the broker is able to reload config files like artemis-roles.properties without a restart, why do you need to restart the broker pod when the configmap changes?

**Comment by mattlegall** [comment]
@brusdev I was not aware of the automatic reload.

I finally tested auto-reload (by adding some addresses) but it doesn't work in my context.
I must delete the pod so that it restarts and then I see the additional addresses.
I also tried to delete the ConfigMap broker-xml-cm and recreate it with additional addresses, but auto-reload doesn't work either. I also tried to add new annotations the ConfigMap broker-xml-cm, but auto-reload doesn't work either.

I am attaching a simplified version of the two relevant files of my setup to try to understand why auto-reload doesn't work.

Any idea is welcome!

Thx

[ActiveMQArtemis.txt](https://github.com/artemiscloud/activemq-artemis-operator/files/11102051/ActiveMQArtemis.txt)
[broker-xml-cm.txt](https://github.com/artemiscloud/activemq-artemis-operator/files/11102080/broker-xml-cm.txt)

**Comment by brusdev** [comment]
@mattlegall what broker/operator version are you using?

**Comment by mattlegall** [comment]
@brusdev we are using operator artemiscloud/activemq-artemis-operator:1.0.10 and and broker artemiscloud/activemq-artemis-broker-kubernetes:1.0.9

**Comment by brusdev** [comment]
@mattlegall activemq-artemis-operator:1.0.11 and artemiscloud/activemq-artemis-broker-kubernetes:1.0.15 should fix the auto reload, could you try?

**Comment by mattlegall** [comment]
@brusdev ok will upgrade to activemq-artemis-operator:1.0.11 and artemiscloud/activemq-artemis-broker-kubernetes:**1.0.11** "only" fix the auto-reload issue? I am trying not to jump directly from 1.0.9 (2.26) to 1.0.15 (2.28)

**Comment by mattlegall** [comment]
@brusdev I did some further testing. Auto-reload works if I 'exec' into the pod and manually edit the broker.xml or if I 'touch' the broker.xml in case of modulised broker.xml (as described here https://activemq.apache.org/components/artemis/documentation/latest/configuration-index.html#reloading-modular-configuration-files)

The issue is actually that the operator doesn't relay an update of the extraMounts config maps back into the actual file into the pod. For instance, in the example below, if I update broker-xml-cm config map, then etc/broker.xml doesn't get updated.
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
spec:
  deploymentPlan:
    extraMounts:
      configMaps:
      - artemis-profile-cm
      - artemis-roles-properties-cm
      - artemis-users-properties-cm
      - bootstrap-xml-cm
      - broker-acceptors-xml-cm
      - broker-bridges-xml-cm
      - broker-connectors-xml-cm
      - broker-diverts-xml-cm
      - broker-security-settings-xml-cm
      - broker-xml-cm
      - cert-roles-properties-cm
      - cert-users-properties-cm
      - jolokia-access-xml-cm
      - logging-properties-cm
      - login-config-cm
      - management-xml-cm

In this use case, it is expected that auto-reload doesn't work because the actual copy from broker-xml-cm to broker.xml file is happening in our custom broker init image. And therefore pod restart is a must.

So unless you can think of an alternative, I think "Support for adding custom annotations to the broker statefulset" is the only option.

**Comment by brusdev** [comment]
@mattlegall sorry I misunderstood your issue, I thought you was talking about the config map created by the operator for the broker properties. You could cause a restart using an environment variable, in this way you have full control of restart and you can restart after all config maps has been updated, i.e.

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-env-restart
spec:
  deploymentPlan:
    size: 2
  env:
    - name: RESTART_TIMESTAMP
      value: '1680284809'
```

```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-env-restart
spec:
  deploymentPlan:
    size: 2
  env:
    - name: RESTART_TIMESTAMP
      value: '1680284819'
```

**Comment by mattlegall** [comment]
@brusdev It is working using the environment variable. Thanks
