### ISSUE TITLE
provide a way to easily extend the classpath of the broker

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#562]
To use jdbc persistence, currently requires an init container. broker properties can now replace the xml config changes, however getting the jdbc client jars on the classpath is problematic without an init container.

One thought of using a config map with -cp postfix is not a flyer b/c jars will typically be too large for etcd. ( > 1M)
However having something similar for an extra mount may make sense. An extra mount with some postfix or annotation can be added to the classpath of the broker or the lib directory or lib extra directory.

There is one caveat, the broker run command creates an isolation classloader for the broker, which means that any jar on the classapth won't have access to artemis interfaces, so a plugin jar would need to be in the lib directory.
An agent jar would need to be on the classpath and some way to disable the isolation classloader would work. (The jolokia jvm agent needing access to the Artemis JAAS callback handler is a concrete use case).
A jdbc jar would work on the classpath or in the lib dir as it has no need to callback to any artemis interface.

We may want to fully manage the classpath of the broker, ie: avoid the run command, or have some Artemis option to disable the isolation class loader.

**Comment by brusdev** [comment]
Allow broker classpath extension using custom paths
https://issues.apache.org/jira/browse/ARTEMIS-4444

**Comment by gtully** [comment]
The combination of the resource templates allowing the provision of a custom init container that can copy resources and the ARTEMIS-4444 classpath extension will suffice for this use case.
