### ISSUE TITLE
Jolokia client should use pod's hostname instead of ip address

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#565]
Currently jolokia client uses pod ip to contact broker for managment operations.
This doesn't work when broker web console is configured with ssl + sniHost check.
The pod IP is dynamically allocated and is not suitable for such a case. Instead it should
be using host name.

**Comment by moritzschmitz-oviva** [comment]
What is the workaround here? For me this means the operator cannot do anything on the broker.

**Comment by gaohoward** [comment]
In next release the sniHostCheck will be disabled by default. See this commit https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/commit/ba5d069c5e1927a69f6c132c24f3e0332fbbf317
right now you can manually do it using custom init image.
