### ISSUE TITLE
Add tool to convert an ActiveMQ Artemis CR instance to a jinja template for YamlConfiger

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-operator#6]
**Is your feature request related to a problem? Please describe.**
With the move to generating broker configuration via the [YamlConfiger](https://github.com/rh-messaging-qe/YamlConfiger) tool a way to get the users desired configuration from the custom resource and into an appropriate template is required. 

**Describe the solution you'd like**
An independently buildable cr2jinja tool can be added to the operator's tools directory like the previously added csv-gen tool. This tool can then be built independently yet depend on other aspects of the operator codebase such as the CRD's and associated go side structs.

**Describe alternatives you've considered**
Originally the thought here was that this would be internal to the operator itself and the functionality would not be exposed externally. However it is also desired to make the tool generally useful in concert with the YamlConfiger tool for configuring ActiveMQ Artemis brokers in general, whether running within kubernetes or not. Being able to be built and executed independently will allow for usage independent of deployment on kubernetes.

**Comment by gaohoward** [comment]
close as fixed/merged.
