### ISSUE TITLE
Support ARM64 Arch

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#601]
**Is your feature request related to a problem? Please describe.**

To include arm64 support in multi-arch build.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by brusdev** [comment]
Build multi-arch container images
https://github.com/artemiscloud/activemq-artemis-broker-image/issues/28
https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/issues/68
https://github.com/artemiscloud/activemq-artemis-broker-init-image/issues/35

**Comment by brusdev** [comment]
The arm64 support will be included in v1.0.14
