### ISSUE TITLE
Error while following the documentation to deploy operator examples.

### ISSUE THREAD

**Issue by SantoshKumarA** [artemiscloud/activemq-artemis-operator#612]
**Describe the bug**
The documentation at https://artemiscloud.io/docs/tutorials/using_operator/#step-3---deploying-activemq-artemis-broker-in-the-cloud says the following,
kubectl create -f examples/artemis-basic-deployment.yaml -n myproject

But, under examples, one do not find the above yaml file specified at 
https://github.com/artemiscloud/activemq-artemis-operator/tree/main/examples.

Would you please upload the yaml file, so that can continue the documentation to have a complete hello world example flow. Thank you.

**Screenshots**
$ kubectl create -f examples/artemis-basic-deployment.yaml -n myproject
**error**: the path "examples/artemis-basic-deployment.yaml" does not exist

Thank you. Looking forward for your quick help. (if unable to fix in the re-organized structure, at least please share me the file/content. 😊)

**Comment by brusdev** [comment]
@SantoshKumarA I created the following PR to fix the doc, could you review it?
https://github.com/artemiscloud/activemq-artemis-operator/pull/613

**Comment by brusdev** [comment]
Fixed by #613
