### ISSUE TITLE
update operator-utils dependency to v1.4.12

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#619]
the logging of the equals methods for the map comparator is gated with debug level in .12 which tidies up our logs.
https://github.com/RHsyseng/operator-utils/releases/tag/v1.4.12

**Comment by brusdev** [comment]
@gtully I'm going to revert the commit related to this issue that upgrades github.com/RHsyseng/operator-utils to v1.4.12 because it is causing #643. I created the issue for github.com/RHsyseng/operator-utils: https://github.com/RHsyseng/operator-utils/issues/110

**Comment by brusdev** [comment]
The fix for https://github.com/RHsyseng/operator-utils/issues/110 was included in github.com/RHsyseng/operator-utils to v1.4.12.1

@gtully do we still need to update github.com/RHsyseng/operator-utils after #649 ?

**Comment by gtully** [comment]
no, we are sorted with that filter.
