### ISSUE TITLE
No option to enable AMQ_ENABLE_METRICS_PLUGIN

### ISSUE THREAD

**Issue by FrankMormino** [artemiscloud/activemq-artemis-operator#62]
**Describe the bug**
This is an option that's avail on the image itself but not on the operator.

**Expected behavior**
Ability to enable AMQ_ENABLE_METRICS_PLUGIN from the operator yaml

**Additional context**
Optional. Add any other context about the problem here.

**Comment by gaohoward** [comment]
https://issues.redhat.com/browse/ENTMQBR-4756

**Comment by ThommyH** [comment]
We tried to enable prometheus without much luck, maybe you have an idea what we are missing?

We extended the base image to copy metrics.war to `/opt/amq/web/metrics.war` and added `/opt/amq/lib/artemis-prometheus-metrics-plugin-1.1.0.jar`.
As for configuration, we added `<app url="metrics" war="metrics.war"/>` to /home/jboss/amq-broker/etc/bootstrap.xml.

The server boots, loads metrics plugin
`2021-11-26 11:44:42,507 WARN  [org.apache.activemq.artemis.core.server] AMQ222291: The metrics-plugin element is deprecated and replaced by the metrics element
2021-11-26 11:44:42,510 INFO  [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}`

But curling http://instancename.hdsv.ns.svc.cluster.local:8161/metrics returns blank. Do we need to add additional config somewhere?

**Comment by gaohoward** [comment]
Can you try http://instancename.hdsv.ns.svc.cluster.local:8161/metrics/ (adding a slash at the end in your url)

**Comment by gaohoward** [comment]
@ThommyH and make sure you follow this guide http://instancename.hdsv.ns.svc.cluster.local:8161/metrics

**Comment by ThommyH** [comment]
@gaohoward /metrics/ did work! thank you

**Comment by gaohoward** [comment]
@ThommyH np, glad it works for you.

**Comment by mycroft11** [comment]
> We tried to enable prometheus without much luck, maybe you have an idea what we are missing?
> 
> We extended the base image to copy metrics.war to `/opt/amq/web/metrics.war` and added `/opt/amq/lib/artemis-prometheus-metrics-plugin-1.1.0.jar`. As for configuration, we added `<app url="metrics" war="metrics.war"/>` to /home/jboss/amq-broker/etc/bootstrap.xml.
> 
> The server boots, loads metrics plugin `2021-11-26 11:44:42,507 WARN [org.apache.activemq.artemis.core.server] AMQ222291: The metrics-plugin element is deprecated and replaced by the metrics element 2021-11-26 11:44:42,510 INFO [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}`
> 
> But curling http://instancename.hdsv.ns.svc.cluster.local:8161/metrics returns blank. Do we need to add additional config somewhere?

Hi @ThommyH , could you please post an example on how you customized the base template to include the metrics functionality? Much appreish!

**Comment by ThommyH** [comment]
You are almost there, you have to curl  http://instancename.hdsv.ns.svc.cluster.local:8161/metrics/ with trailing /.

We use a servicemonitor like this:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: kube-prometheus
  name: artemis-collector
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics/ <<<<<<<<<<<<< important
    port: console-jolokia
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      application: artemis-app

```

**Comment by minhtran-q** [comment]
> We tried to enable prometheus without much luck, maybe you have an idea what we are missing?
> 
> We extended the base image to copy metrics.war to `/opt/amq/web/metrics.war` and added `/opt/amq/lib/artemis-prometheus-metrics-plugin-1.1.0.jar`. As for configuration, we added `<app url="metrics" war="metrics.war"/>` to /home/jboss/amq-broker/etc/bootstrap.xml.
> 
> The server boots, loads metrics plugin `2021-11-26 11:44:42,507 WARN [org.apache.activemq.artemis.core.server] AMQ222291: The metrics-plugin element is deprecated and replaced by the metrics element 2021-11-26 11:44:42,510 INFO [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}`
> 
> But curling http://instancename.hdsv.ns.svc.cluster.local:8161/metrics returns blank. Do we need to add additional config somewhere?



> We tried to enable prometheus without much luck, maybe you have an idea what we are missing?
> 
> We extended the base image to copy metrics.war to `/opt/amq/web/metrics.war` and added `/opt/amq/lib/artemis-prometheus-metrics-plugin-1.1.0.jar`. As for configuration, we added `<app url="metrics" war="metrics.war"/>` to /home/jboss/amq-broker/etc/bootstrap.xml.
> 
> The server boots, loads metrics plugin `2021-11-26 11:44:42,507 WARN [org.apache.activemq.artemis.core.server] AMQ222291: The metrics-plugin element is deprecated and replaced by the metrics element 2021-11-26 11:44:42,510 INFO [org.apache.activemq.artemis.core.server] AMQ221082: Initializing metrics plugin org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin with properties: {}`
> 
> But curling http://instancename.hdsv.ns.svc.cluster.local:8161/metrics returns blank. Do we need to add additional config somewhere?

Hi @ThommyH,

I'm also trying to expose the metrics of the broker. Do I need to rebuild the `quay.io/artemiscloud/activemq-artemis-broker-init` image when adding the `artemis-prometheus-metrics-plugin-1.1.0.jar`?

**Comment by brusdev** [comment]
The artemis-prometheus-metrics-plugin is included in the broker kubernetes image since activemq-artemis-broker-kubernetes-image v1.0.11, see https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/pull/46

**Comment by gauravtayade11** [comment]
Hi guys i am trying to enable the metrics of artemis active mq i tried all the jar but not getting any metrics can anyone help me with that ?

**Comment by brusdev** [comment]
@gauravtayade11 can you share your ActiveMQArtemis CR?

**Comment by brusdev** [comment]
@gauravtayade11 you are getting a blank page because the url should finish with `/`, i.e.
```
http://instancename.hdsv.ns.svc.cluster.local:8161/metrics/
```

Anyway, you don't need to extend the base image try the following CR:
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-test
spec:
  deploymentPlan:
    enableMetricsPlugin: true
```

```
curl -v http://artemis-test-ss-0.artemis-test-hdls-svc.default.svc.cluster.local:8161/metrics/
```

**Comment by gauravtayade11** [comment]
@brusdev can you any article so i can refer from scratch like manifest file or any other

**Comment by brusdev** [comment]
@gauravtayade11 I added a working ActiveMQ Artemis CR to enable metrics in my previous comment, see https://github.com/artemiscloud/activemq-artemis-operator/issues/62#issuecomment-1570479760

What issue are you getting with that CR?

**Comment by gauravtayade11** [comment]
@brusdev i am using normal deployment in k8s cluster to deploy a artemis

**Comment by brusdev** [comment]
@gauravtayade11 this project is to deploy ActiveMQ Artemis using an operator. You could check the deployment created by the operator.

**Comment by gauravtayade11** [comment]
@brusdev can you send me operator link

**Comment by brusdev** [comment]
@gauravtayade11 the quick start page includes all steps to deploy the operator: https://artemiscloud.io/docs/getting-started/quick-start/

**Comment by gauravtayade11** [comment]
@brusdev https://github.com/rh-messaging/artemis-prometheus-metrics-plugin#installing-in-activemq-artemis  i am following this installation

**Comment by brusdev** [comment]
> @brusdev https://github.com/rh-messaging/artemis-prometheus-metrics-plugin#installing-in-activemq-artemis i am following this installation

@gauravtayade11 this guide is for a standalone installation, it is not for the ActiveMQ Artemis Operator

**Comment by gauravtayade11** [comment]
@brusdev i am getting confused regarding the path where to copy the jar and war file

**Comment by brusdev** [comment]
> @brusdev i am getting confused regarding the path where to copy the jar and war file

You should create a discussion/issue in [rh-messaging/artemis-prometheus-metrics-plugin](https://github.com/rh-messaging/artemis-prometheus-metrics-plugin#installing-in-activemq-artemis) if you need help for `artemis-prometheus-metrics-plugin` and not for the ActiveMQ Artemis Operator.
