### ISSUE TITLE
Support cert-manager to secure ingress/route

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#679]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by brusdev** [comment]
Resolved by https://github.com/artemiscloud/activemq-artemis-operator/commit/564fe04294cf78f7f971274b51a33a62e8ed28c6
