### ISSUE TITLE
Support for operator metrics

### ISSUE THREAD

**Issue by robert-mcnamara** [artemiscloud/activemq-artemis-operator#694]
**Is your feature request related to a problem? Please describe.**

It is not documented how to expose metrics from the operator itself.

The Artemis operator is built on-top on the operator-sdk which in turns uses the kube-builder library.
kube-builder has default list of metrics that are available in a Prometheus format.
See for reference: https://book.kubebuilder.io/reference/metrics-reference

When the operator starts up, it starts a metrics endpoint that can be scraped.

**Describe the solution you'd like**

To allow metrics to be scraped, a k8s service and some annotations on the k8s operator deployment are required.
Along with supporting documentation

**Comment by brusdev** [comment]
@robert-mcnamara this enhancement sounds good to me. Are you planning to contribute with a PR?

**Comment by robert-mcnamara** [comment]
@brusdev - thanks for the response, yes I can submit a PR for review early next week

**Comment by brusdev** [comment]
@robert-mcnamara great 🎉

**Comment by brusdev** [comment]
This enhancement will be included in 1.1.0
