### ISSUE TITLE
Adding openshift supported feature annotations

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#706]
**Is your feature request related to a problem? Please describe.**
Those annotations are supported by current OCP and will be required by future OCPs.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Optional. A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Optional. Add any other context or screenshots about the feature request here.

**Comment by brusdev** [comment]
The new  feature annotations will be included in 1.0.16
