### ISSUE TITLE
JMS API set up for artemis EKS cluster

### ISSUE THREAD

**Issue by git-syeda** [artemiscloud/activemq-artemis-operator#727]
Hi team,
We would like to know how to call artemis API url using JMS to perform admin operations. Also please help us with the complete set up on how to connect.

**Comment by brusdev** [comment]
Hi @git-syeda, issues are only to ask for enhancements or bugs. You could create a discussion for questions or to connect, see https://github.com/artemiscloud/activemq-artemis-operator/discussions?discussions_q=jmx.

**Comment by git-syeda** [comment]
sure, i have opened it in the discussions.

**Comment by brusdev** [comment]
thanks
