### ISSUE TITLE
modification to annotations on managed resources should be respected by the operator

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#745]
**Describe the bug**
If a third party annotates one of the operator managed resources, the stateful set for example, that annotation will be lost on a reconcile. We should respect annotations

the resourceTemplate #588 allows annotations to change, but we currently don't update on change for the same reason. When we compare deployed and desired, we need to now consider the objectMeta labels and Annotations.

**Comment by brusdev** [comment]
The fix for this bug will be included in 1.0.17
