### ISSUE TITLE
improve discovery, don't depend on all interfaces list, check just for what we care for

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#760]
The discovery logic lists all apis and searches for particular entries but can run foul of selective availability of some resources.

eg: 

> 2023-12-14T16:18:19.478Z ERROR setup failed in detecting openshift {"error": "unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request"}

We can simplify by just verifying the availability of a single resource that we care about.

**Comment by brusdev** [comment]
The OpenShift detection is not working as expected because discovery.IsResourceEnabled looks for the resource name, i.e. `openshiftapiservers`
