### ISSUE TITLE
Create queues on all broker pods in an eks cluster using jolokia API URL at once.

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#769]
Hi Team,

Can you suggest how can we create a queues or any admin operation on all broker pods in an eks cluster using jolokia api url at a time. 
Currently we were able to create queues and perform other operations on individual pod using jolokia api url. But we need a setup to create it on all broker pods at a time with common endpoint url. 
can you please provide some info on this.

**Comment by brusdev** [comment]
Addresses and queues can be created on all broker pods by using broker properties. What other operations are you performing on all broker pods with common endpoint url?

**Comment by gnaveen33** [comment]
@brusdev , right now we use jolokia api url to create queues and addresses on each individual broker pods.
But our requirement is, we have to create addresses and queues at a single shot on all broker using API call. 
How to acheive that?
What config changes we have to make and where?

**Comment by gnaveen33** [comment]
for a particular namespace, on all boker pods we have to perform one operation a give time and not through induvidual broker pod jolokia api url.

**Comment by gnaveen33** [comment]
> Addresses and queues can be created on all broker pods by using broker properties. What other operations are you performing on all broker pods with a common endpoint url?

Hwo to achive this common endpoint url? is there any way to do that ?

**Comment by brusdev** [comment]
@gnaveen33 broker properties doesn't require a common endpoint url, they can be defined int the ActiveMQArtemis CR itself or in an extra secret, see https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#configuring-brokerproperties

**Comment by gnaveen33** [comment]
@brusdev, Can you be more specific please?
What config we have to define in ActiveMQArtemis CR ? so that, if we create queues on one broker pod it will be reflecting on all other broker pods running under a namespace.

**Comment by gnaveen33** [comment]
@brusdev thanks for the update. Suppose if I'm going to create another queue means we have to again update/edit the broker properties?

Also, right now we are using jolokia API url (specific to each broker pod ) to perform queue related operation like create, delete, browse via jenkins pipeline. 
Now our requirement is to perform queue operation on all the pod at the same time using a common url via jenkins. Please suggest us a way on this.

**Comment by gaohoward** [comment]
There is no common url or api of jolokia that can do this. Each broker has its own jolokia endpoint. So I guess you have to use each jolokia endpoint to create your queues to each broker. i.e. you loop through every jolikia endpoint to invoke the create queue command.

**Comment by gnaveen33** [comment]
@gaohoward @brusdev , thanks for all your suggestions.
