### ISSUE TITLE
Add anti-affinity support

### ISSUE THREAD

**Issue by bjetal** [artemiscloud/activemq-artemis-operator#77]
**Is your feature request related to a problem? Please describe.**

I need to make sure pods for an Artemis cluster are running on different nodes so a single node failure doesn't take the whole cluster down.

**Describe the solution you'd like**

I would like the ability to configure pod anti-affinity (and possibly affinity and tolerations as well) in the CR for the cluster.  The anti-affinity configuration should probably have two settings:
* Whether to use anti-affinity (boolean).  I assume the default would be not to use it to keep compatibility.
* An optional node label name to use for anti-affinity (default should be the `kubernetes.io/hostname`).

Affinity and toleration configuration could use the normal Pod structures for those configurations.

**Comment by brusdev** [comment]
Done by #158
