### ISSUE TITLE
openmessaging benchmark is functional for Artemis ?

### ISSUE THREAD

**Issue by achinjain214** [artemiscloud/activemq-artemis-operator#777]
I see a repo already there for artemis-driver :
https://github.com/openmessaging/benchmark/blob/master/driver-artemis/

If someone has already run performance tests using openmessaging benchmark any help would be much appreciated?

**Comment by brusdev** [comment]
@achinjain214 this project is related to the operator, while your request is related to the operand Apache ActiveMQ Artemis, see https://github.com/apache/activemq-artemis
