### ISSUE TITLE
podAntiAffinity weight shoud not be required

### ISSUE THREAD

**Issue by Raschmann** [artemiscloud/activemq-artemis-operator#786]
As it is described here, weight shoud not be used when statefull set pod is scheduled; therefore parameter weight in CRDS should not be defined as required:
https://github.com/kubernetes/kubernetes/issues/57002

**Comment by brusdev** [comment]
@Raschmann my understanding is that the field `weight` should not be used [when using requiredDuringSchedulingIgnoredDuringExecution](https://github.com/kubernetes/kubernetes/issues/57002#issuecomment-358560178).
Indeed in the CRDs the field `weight` is required only for `preferredDuringSchedulingIgnoredDuringExecution`, see:
https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.16/deploy/crds/broker_activemqartemis_crd.yaml#L507
https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.16/deploy/crds/broker_activemqartemis_crd.yaml#L658
https://github.com/artemiscloud/activemq-artemis-operator/blob/v1.0.16/deploy/crds/broker_activemqartemis_crd.yaml#L831
