### ISSUE TITLE
Patching pvc to increase size shuts down artemis instances

### ISSUE THREAD

**Issue by adlnc** [artemiscloud/activemq-artemis-operator#792]
Hi,

I'm using the operator to manage multiple instances of artemis on a my kubernetes clusters.
Versions:
artemiscloud/activemq-artemis-operator:1.0.16
artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.31.2

I manage these instances using helm charts for both artemis operator but also I use an another one that wraps artemis CRDs in order to customize these instances. 
I don't override much from the defaults, apart from probes, persistenceEnabled to true and deployment Size to 2 replicas and a few more but I don't think relevant to my issue. 

So, Artemis instances use persistent volumes to store data. 
If I initially create a volume of 10Gi for instance, and want to patch these volumes in order to increase the size. 
ie: `kubectl patch PVC -p '{"spec":{"resources":{"requests":{"storage":"50Gi"}}}}'`
From k8s pov resize works fine.
Now if I update the activemqartemis CRD to match that new size, both replicas of activemq are killed, then after a few seconds, re-created by the operator but I feel like it doesn't really seem necessary. Is this considered a bug or am I missing something here ?

Thanks

**Comment by brusdev** [comment]
@adlnc the operator is working as expected because it uses StatefulSets to deploy the broker pods and there is no way to change volumeClaimTemplates of a StatefulSet without deleting it and creating it again.
I would suggest to disable temporary the reconciliation setting the field `spec.version` to `DISABLE` and then manually applying the procedure described at https://evgenijohn.medium.com/statefulsets-resizing-pvc-25194e9087b7

**Comment by adlnc** [comment]
I see... Thanks for this link. I really was unfamiliar with this `kubectl delete --cascade=orphan` option until now.
Makes more sense now but kinda leave me curious about the benefits of using volumeClaimTemplates directly from STS instead of a in independent PVC resource. 
But anyway thanks for your time

**Comment by brusdev** [comment]
@adlnc the StatefulSet pod template is the same for all replicas so using an independent PVC resource would mean share the same PVC for all replicas.
