### ISSUE TITLE
go.mod support is broken due to missing tags in openshift/api

### ISSUE THREAD

**Issue by mkrutov** [artemiscloud/activemq-artemis-operator#8]
**Describe the bug**
go.mod mentions v3.9.0 openshift/api version. 
this tag doenst' exist in openshift/api: https://github.com/openshift/api/issues/647

**To Reproduce**
1. try to build

**Platform (please complete the following information):**
not relevant

**Expected behavior**

**Comment by mkrutov** [comment]
https://github.com/openshift/api/tree/release-3.9 ?

**Comment by redmark-alt** [comment]
We see the same issue setting up some new GO testing environments.

go: github.com/artemiscloud/activemq-artemis-operator@v0.17.0 requires
	github.com/openshift/api@v3.9.0+incompatible: reading github.com/openshift/api/go.mod at revision v3.9.0: unknown revision v3.9.

Is there a workaround?

Thanks,

**Comment by brusdev** [comment]
@mkrutov @redmark-redhat is this issue still valid?

**Comment by redmark-redhat** [comment]
@brusdev I would guess it is not valid.

**Comment by brusdev** [comment]
thanks for your feedback
