### ISSUE TITLE
AMQ Broker Operator 7.8.1 broken in OperatorHub

### ISSUE THREAD

**Issue by vdrvergara** [artemiscloud/activemq-artemis-operator#81]
**Describe the bug**
Deployment in crasloopback state due missing field in openAPIV3Schema.

**To Reproduce**
1. Go to OperatorHub in Openshift container platform
2. Install AMQ Broker Operator
3. Deployment doesn't conclude due error: panic: runtime error: index out of range [0] with length 0 [recovered]
4. Describe crd activemqartemises.broker.amq.io and get the message: 
  Message:               [spec.versions[0].schema.openAPIV3Schema.type: Required value: must not be empty at the root, spec.versions[1].schema.openAPIV3Schema.type: Required value: must not be empty at the root, spec.versions[2].schema.openAPIV3Schema.type: Required value: must not be empty at the root]
**Platform (please complete the following information):**
[amqCRD.txt](https://github.com/artemiscloud/activemq-artemis-operator/files/6555878/amqCRD.txt)

 - OS: Openshift Container Platform
 - Version 4.6.21
 - Go [e.g. 1.13.4

**Comment by brusdev** [comment]
This issue will be closed because it has not been updated for a long time.
