### ISSUE TITLE
Can't addrole using JMX API call

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#818]
Hi Team,

We are not able to **addrole** to the address/queues. 
Can you please help us with right API call using jolokia endpoint ?
 
Please find below sample call ,

{
	"type":"exec",
"mbean":"org.apache.activemq.artemis:broker=\"****\",component=addresses,address=\"***\""
,"operation":"addRole()"
}

Exception :
{
	"request": {
		"mbean": "org.apache.activemq.artemis:address=\"****\",broker=\"****\",component=addresses",
		"type": "exec",
		"operation": "addRole()"
	},
	"error_type": "java.lang.IllegalArgumentException",
	"error": "java.lang.IllegalArgumentException : No operation addRole found on MBean org.apache.activemq.artemis:address=\"***\",broker=\"****\",component=addresses",
	"status": 400
}

**Comment by brusdev** [comment]
@gnaveen33 this is a question for the Apache ActiveMQ Artemis project, I'll suggest to send an email to users@activemq.apache.org

**Comment by brusdev** [comment]
This issue was discussed at https://lists.apache.org/thread/5jmhn6gs8wx3mt4n4bvhc4l8s0yt25k1
