### ISSUE TITLE
Support per broker configuration for brokerProperties in -bp suffix secrets

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#821]
**Describe the feature**
broker-N currently not working if specified in the secret with -bp secrets

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by gaohoward** [comment]
broker-N currently not working if specified in the secret with -bp secrets

**Comment by brusdev** [comment]
This enhancement will be included in 1.2.0
