### ISSUE TITLE
Port 8161 redirection to port 80

### ISSUE THREAD

**Issue by javadan** [artemiscloud/activemq-artemis-operator#825]
I'm trying to set up Artemis in minikube, with console access from another machine.

So I have an nginx forwarding port 9000 to my ingress controller.
However, when I try to access it via 9000, which forwards to 8161, curl -L redirects to port 80.

So I got it working in the end by opening port 80, to forward to a nodeport 30161 that forwards to 8161 internally, and then when it redirects to 80, it finds it.  

Seems messy though.  Does anyone have a better plan for accessing the console?  Is it possible to disable the port 80 redirection?

**Comment by brusdev** [comment]
@javadan I already answered your question on stackoverflow, see https://stackoverflow.com/questions/78041718/nginx-configuration-for-accessing-activemq-artemis-web-console-inside-minikube/78042318#78042318

You can create an ingress resource by setting the `spec.console.expose` field to true, i.e.
```
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: my-artemis
spec:
  console:
    expose: true
    ingressHost: my-artemis.my-domain.io
```

```
$ curl -Lv --proxy http://192.168.49.2:80 http://my-artemis.my-domain.io
```

I created a nigix container based on the config of your [stackoverflow question](https://stackoverflow.com/questions/78041718/nginx-configuration-for-accessing-activemq-artemis-web-console-inside-minikube) and it worked. I only changed the proxy_pass parameter to `<MINIKUBE IP>:80`, i.e.
```
$ docker run --name my-nginx --rm -it --network host -p 19000:19000 -v ./nginx.conf:/etc/nginx/nginx.conf:ro nginx

$ curl -Lv --proxy http://localhost:19000 http://my-artemis.my-domain.io
```

**Comment by javadan** [comment]
Hi @brusdev 
Ah, I see.  My confusion came from `spec.console.expose` exposing port 80, while the Artemis console docs and logs expose on port 8161.

I got it working now without the hacky loopback, by just forwarding nginx port 80 to proxy pass through to minikube-IP port 80.  It's a bit confusing that this works though, because I'm entirely bypassing my minikube ingress nginx, and there's no port 80 exposed by any service according to `kubectl get all`, 

So, now the solution is to run it on port 80 internally, and proxy pass 80 through to the internal 80.  

But this puts my understanding of proxy passing in doubt. 

```
NAME                                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller             NodePort    10.111.12.119   <none>        80:32076/TCP,443:30195/TCP   18d

```

To access my services, the host's NGINX passes 19000 through to 32076 which is my minikube ingress port, and then the config pattern-matches the sub-URL to find the service port.  

But for the Artemis console, I'm now hitting the host's NGINX port 80, which I've got forwarding to minikube-ip:80, and yet there's no port 80 exposed by the ingress-nginx controller, and no nodeport service?  So how am I able to proxy pass through a port that isn't open?

**Comment by javadan** [comment]
Or perhaps, assuming it's hidden by the operator, how do i see what ports the operator has exposed ?

**Comment by brusdev** [comment]
@javadan the operator doesn't hide the console port. When the field `spec.console.expose` is true the operator create an ingress resource to expose the port 8161 of the broker pod. Your issue is not fully clear to me, can you provide a simple reproducer as the example in my [answer](https://github.com/artemiscloud/activemq-artemis-operator/issues/825#issuecomment-1988705653)?

**Comment by brusdev** [comment]
The redirection to the `http://myip.localnet.com/console` is caused by the minikube ingress controller that is expose on the port 80 of the minikube IP. You can easily fix that issue using the `proxy_redirect` directive, i.e.
```
    server {
        listen       19000;
        listen       [::]:19000;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
            proxy_pass http://192.168.58.2:32076; # Ingress controller port
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_redirect http://$host/ http://$host:19000/;
...
```
