### ISSUE TITLE
Allow change to access storage mode

### ISSUE THREAD

**Issue by scotchr** [artemiscloud/activemq-artemis-operator#840]
The storage mode for the brokers seems to be hard coded to "ReadWriteOnce", It would be better to allow this to be set in the storage section of the broker configuration so the (for example) ReadWriteMany could be specified for the stateful set

**Comment by brusdev** [comment]
Hi @scotchr, could you add a use case to the issue description that requires other storage modes than `ReadWriteOnce`?

**Comment by scotchr** [comment]
Hi @brusdev , the use case is as follows:

For storage we use the trident driver to mount a NetApp volume, this is obviously a NAS so could be mounted by any node, the use of ReadWriteOnce limits the volume so that it can be only mounted on a single node. If we have a problem with a node then we'd want to move that Artemis POD onto a new node, with ReadWriteOnce we can't do this as it is tied to the individual (failed) node ( https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes )

Thanks for the "patch" tip I'll use that
