### ISSUE TITLE
add a tutorial for the send receive usecase

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-operator#867]
**Describe the feature**

Write a new tutorial for the send and receive usecase over minikube.

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
Resolved by https://github.com/artemiscloud/activemq-artemis-operator/commit/8d4fa779d2277455bd0d584e6c4f59ebb77bc3c3
