### ISSUE TITLE
Temporary queues in artemis

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#871]
Hello Team, 
We have the below questions on temporary queues in Artemis MQ in EKS. Could you please help us with answers for the below ones.

- When are temporary queues used

- How are temporary queues created?

- Is there any API call to create temporary queue using JMX?

- How do we keep track of the temp queues that get created/deleted? 

- How can granular access management for temp queues be specified

**Comment by brusdev** [comment]
@gnaveen33 those are questions for Apache ActiveMQ Artemis, you should send an eimail to users@activemq.apache.org after reading the documentation https://activemq.apache.org/components/artemis/documentation/latest/address-model.html#temporary-queues

**Comment by gnaveen33** [comment]
thanks for the update @brusdev

**Comment by brusdev** [comment]
@gnaveen33 I see you send an email to users@activemq.apache.org and got a few replies see https://lists.apache.org/thread/9h2sdp7y5kg05p8qy77d5clnn8v1jkk2
