### ISSUE TITLE
Add Deprecation to Address CR in favour of Artemis.Spec.brokerProperties

### ISSUE THREAD

**Issue by gtully** [artemiscloud/activemq-artemis-operator#877]
brokerProperties an -bp secrets provide a consistent, reliable and extensible way to specify addresses and queues that makes use of artemis config reload from disk.
see example: https://github.com/artemiscloud/activemq-artemis-operator/blob/8d36322afb9befe5187c3bc61eba6491917ae6e3/examples/address/artemis_broker_properties_address.yaml#L7

**Comment by brusdev** [comment]
The field `spec.brokerProperties` of the ActiveMQArtemis CR can replace ActiveMQArtemisAddress CR allowing a single source of truth for a deployment of ActiveMQ Artemis on Kubernetes.

The brokerProperties secrets (with the suffic -bp) are only an alternative of the the field `spec.brokerProperties` to split the brokerProperties accross multiple files if that is required.
