### ISSUE TITLE
Nginx controller's message distribution

### ISSUE THREAD

**Issue by gnaveen33** [artemiscloud/activemq-artemis-operator#888]
Hi Team,

We have a namespace that contains three broker pods. Nginx controller distributes the traffic among the pods. But, when one pod goes down, messages are still routed to the unavailable pod, and we get error. This is not the expected behavior. We would like to have the nginx route messages only to the healthy pods in case of any of the pods go down. Could you please help us on achieving this?

Thanks,
Naveen

**Comment by gnaveen33** [comment]
Hi @brusdev,

We are not supposed to send/upload the dump files, is it possible to get a sample file so that I can compare with my existing setup?

Thanks ,
Naveen

**Comment by brusdev** [comment]
@gnaveen33 you can take a look at https://github.com/brusdev/activemq-artemis-tutorials/blob/main/oracle-jdbc-shared-store/ext-acceptor-minikube-install.yaml

**Comment by gnaveen33** [comment]
Thanks for the update @brusdev .

**Comment by gnaveen33** [comment]
Thanks for the Inputs
