### ISSUE TITLE
Add a way to get the total cluster queue length from the management console

### ISSUE THREAD

**Issue by lavifb** [artemiscloud/activemq-artemis-operator#892]
We use [KEDA](https://keda.sh/docs/2.13/scalers/artemis/) for scaling the consumer of our artemis queues. Unfortunately, the management endpoint that they hit only returns the queue length for that artemis node. This makes autoscaling using KEDA untenable while also running an artemis cluster.

**Comment by lavifb** [comment]
original question: https://github.com/artemiscloud/activemq-artemis-operator/discussions/889

**Comment by brusdev** [comment]
@lavifb I tried to design a solution to aggregate the metrics of the broker pods related to an ActiveMQArtemis CR but the solution is not easy and it would require an agent that polls the broker pods for the updated metrics.

Agents that scrap and aggregate metrics already exist like Prometheus and it is already supported, see https://github.com/artemiscloud/activemq-artemis-operator/blob/main/docs/help/operator.md#monitor-broker-metrics-by-using-prometheus

KEDA already supports Prometheus, see https://keda.sh/docs/1.4/scalers/prometheus/

Feel free to reopen the issue if this solution doesn't work for your use case.

**Comment by lavifb** [comment]
Prometheus would probably work but it adds an extra layer in between and make the scaling less responsive. I wonder if instead it would make sense to try to get KEDA to poll both and aggregate there
