### ISSUE TITLE
[FAIL] artemis controller with cert manager test FAILS on power-architecture(ppc64le)

### ISSUE THREAD

**Issue by shubham-bhagwat0** [artemiscloud/activemq-artemis-operator#961]
_we tried to reproduce the build till version 1.2.1 and everything was working correctly,
on 1.2.2 a couple of test cases seem to be failing.
Reporting it to fix a fix or a workaround it_

### Steps to recreate:

- cloning 1.2.2 version
- building the repo using **make build**
- then while running **make test** the following errors are observed

### Summarizing 2 Failures:
  [FAIL] artemis controller with cert manager test certificate rotation [It] broker certificate rotation [controller-cert-mgr-test, certificate]
  /home/activemq-artemis-operator/controllers/activemqartemis_controller_cert_manager_test.go:344
  [FAIL] artemis controller with cert manager test certificate rotation [It] broker issuer certificate rotation [controller-cert-mgr-test, certificate]
  /home/activemq-artemis-operator/controllers/activemqartemis_controller_cert_manager_test.go:484

Ran 191 of 192 Specs in 131.794 seconds
FAIL! -- 189 Passed | 2 Failed | 0 Pending | 1 Skipped
--- FAIL: TestAPIs (131.80s)

[failures observed on 1.2.2.txt](https://github.com/user-attachments/files/15885981/failures.observed.on.1.2.2.txt)
[complete-log.txt](https://github.com/user-attachments/files/15886007/complete-log.txt)

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
@shubham-bhagwat0 I confirm your findings, those test failures will be resolved in 1.2.3 by https://github.com/artemiscloud/activemq-artemis-operator/commit/51b137a04720fde7a88aadc43c7b6a6cc1513f23

**Comment by shubham-bhagwat0** [comment]
@brusdev 
alright, will deploy till v1.2.1 then
thanks for the quick response
