### ISSUE TITLE
Update go-toolset

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#975]
**Describe the bug**

The new go-toolset version is avaliable https://catalog.redhat.com/software/containers/rhel8/go-toolset/5b9c810add19c70b45cbd666?architecture=amd64&image=668b53462d6e902ae131a66d

and should be used

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by brusdev** [comment]
I see that the go version 1.20 is also in: go.mod, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/update.yml and docs/help/building.md. I would be great adding a new steps to .github/workflows/update.yml to update the go version.

**Comment by brusdev** [comment]
Resolved by https://github.com/artemiscloud/activemq-artemis-operator/commit/548d2be3501e8c27b5180bce4473e1c778c19687
