### ISSUE TITLE
CRD env JAVA_ARGS_APPEND fromSource needs to be flagged as invalid

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-operator#981]
**Describe the bug**
The operator currently uses this env var to configure a broker (such as defining custom logging file url)
If use adds the JAVA_ARGS_APPEND in to the spec.env using `ValueFrom` (like from a secret) it will get overridden by the operator. 

> [!TIP]
> Vote this issue reacting with :+1: or :-1:

**Comment by gtully** [comment]
it is not overwritten, pod creation is failing, I guess we don't currently have a way to show this in our status? We have just boolean ready or not for the pod.

create Pod brokermq-ss-0 in StatefulSet brokermq-ss failed error: Pod "brokermq-ss-0" is invalid: spec.containers[0].env[19].valueFrom: Invalid value: "": may not be specified when `value` is not empty
